version: '3'
services:
    web:
        image: spaceface16518/awfice
        environment:
            - SITE_ADDRESS=":80"
        ports:
            - "8080:80"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
volumes:
    caddy_data:
    caddy_config:
